FROM node:lts-alpine as build

WORKDIR /app

COPY /manager/package*.json ./
RUN npm install

COPY /manager/. .
RUN npm run build

FROM nginx

COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]